ice-lab/react-materials

- scaffolds/ice-design-pro/src/layouts/BasicLayout/components/Aside/index.js
> fix: popup disorder when aside change from inline to popup

- components/form/README.md
- components/form/demo/linkage.md
- components/form/package.json
- components/form/src/Form.js
- components/form/src/index.js
- components/form/src/renderField.js
- package.json
https://github.com/alibaba/ice/issues/2142
- display => visible
- form no onChange bug
- css load bug
> fix: change form bug #2142

- scaffolds/ice-design-pro/package.json
- scaffolds/ice-design-pro/src/pages/GeneralTable/components/CustomForm/index.jsx
- scaffolds/ice-design-pro/src/pages/GeneralTable/components/SearchFilter/index.jsx
- scaffolds/ice-design-pro/src/pages/GeneralTable/index.jsx
> fix: formBinder get value && out of memory

- components/label/package.json
- components/label/src/main.scss
> fix: hover style of label

- scaffolds/ice-stark-child/package.json
- scaffolds/ice-stark-layout/package.json
- scripts/scaffolds.js
> feat: add icestark 2 oss

- README.md
- scaffolds/ice-design-pro/package.json
- scaffolds/ice-design-pro/src/utils/request.js
- scaffolds/ice-stark-child/package.json
- scaffolds/ice-stark-child/src/utils/request.js
- scaffolds/ice-stark-layout/package.json
- scaffolds/ice-stark-layout/src/utils/request.js
* 修复 request util 方法中，axios baseUrl 的引用路径
* README 中拼写错误
> Fix: axios base url

- components/panel/package.json
- components/panel/src/main.scss
- components/panel/src/scss/variable.scss
Fix alibaba/ice#2768
移除计算变量后：
移除计算变量前：
> fix: remove color calculate expression

- blocks/BraftEditor/README.md
- blocks/BraftEditor/package.json
- blocks/BraftEditor/src/index.jsx
- blocks/BraftEditor/src/index.module.scss
- blocks/WysiwygEditor/README.md
- blocks/WysiwygEditor/package.json
- blocks/WysiwygEditor/src/index.jsx
- blocks/WysiwygEditor/src/index.module.scss
> new editor blocks（2）

- scaffolds/ice-design-pro/mock/index.js
- scaffolds/ice-design-pro/package.json
- scaffolds/ice-design-pro/src/components/Auth/index.jsx
- scaffolds/ice-design-pro/src/config/dataSource.js
- scaffolds/ice-design-pro/src/config/menu.js
- scaffolds/ice-design-pro/src/layouts/BasicLayout/components/Aside/index.jsx
- scaffolds/ice-design-pro/src/layouts/BasicLayout/components/Header/index.jsx
- scaffolds/ice-design-pro/src/utils/request.js
关联 issue https://github.com/alibaba/ice/issues/2767
* Auth 组件增加 hide children 能力
* 增加菜单权限示例
* 增加异步渲染菜单示例
* icestore 升级 0.3.0
> feat: add menu authority && dynamic menu render example

- scaffolds/ice-design-pro/package.json
- scaffolds/ice-design-pro/src/utils/request.js
> fix: useRequest typo error

- scaffolds/ice-stark-child/package.json
- scaffolds/ice-stark-child/src/config/routes.js
- scaffolds/ice-stark-child/src/global.scss
- scaffolds/ice-stark-child/src/index.jsx
- scaffolds/ice-stark-child/src/layouts/BasicLayout/index.jsx
- scaffolds/ice-stark-child/src/layouts/BasicLayout/index.module.scss
- scaffolds/ice-stark-child/src/router.jsx
- 子应用的全局样式规范
- 路由渲染修复：二级路由不支持 exact、没有 children 时 Route 无用的嵌套
> chore: optimize child app style

- scaffolds/ice-pro/package.json
- scaffolds/ice-pro/src/utils/request.js
* useRequest 中的 request 方法增加返回值，成功时 return response，失败时 throw error，返回值格式与单独的 request 方法保持一致
关联 issue: https://github.com/ice-lab/react-materials/pull/151#issuecomment-544341084
> feat: useRequest add return value in request method

- components/balloon-confirm/index.d.ts
- components/container/index.d.ts
- components/container/package.json
- components/form-binder/index.d.ts
- components/img/index.d.ts
- components/img/package.json
- components/label/index.d.ts
- components/label/package.json
- components/qrcode/index.d.ts
- components/qrcode/package.json
- components/title/index.d.ts
- components/title/package.json
- add d.ts for container
- fix TS error in form-binder
- add d.ts for img
- add d.ts for title
- add d.ts for qrcode
- add d.ts for label
> feat: add d.ts for components

- scaffolds/ice-stark-layout/mock/index.js
> chore(*): change to another avatar

- blocks/ComplexProgressTable/src/CreateFuncDialog.jsx
- blocks/OperationTable/src/DialogDecorator.js
- scaffolds/ice-lite/package.json
- scaffolds/ice-pro/package.json
- scaffolds/ice-stark-child/package.json
- scaffolds/ice-stark-layout/package.json
feat: lite / pro / icestark-layout / icestark-child 四个模板添加 "ideMode": { "name": "ice-react" }
> feat: add ideMode

- scaffolds/ice-admin/package.json
- scaffolds/ice-analysis/package.json
- scaffolds/ice-homepage/package.json
- scaffolds/ice-ts/package.json
add ideMode for all scaffolds [#2965](https://github.com/alibaba/ice/issues/2965)
> feat: add ideMode for all scaffolds

- scaffolds/icestark-child/build.json
- scaffolds/icestark-child/package.json
- scaffolds/icestark-child/src/app.tsx
- scaffolds/icestark-layout/build.json
- scaffolds/icestark-layout/package.json
- scaffolds/icestark-layout/src/app.tsx
> feat: 🎸 turn icestark scaffolds to vite mode

- scaffolds/icestark-layout/build.json
- scaffolds/icestark-layout/package.json
- scaffolds/icestark-layout/src/app.tsx
> fix: 🐛 remove unnecessary option

- scaffolds/ant-design-lite/package.json
- scaffolds/ant-design-lite/tsconfig.json
- scaffolds/icestark-child/package.json
- scaffolds/icestark-child/tsconfig.json
- scaffolds/icestark-layout/package.json
- scaffolds/icestark-layout/tsconfig.json
- scaffolds/midway-faas/package.json
- scaffolds/midway-faas/tsconfig.json
- scaffolds/simple/package.json
- scaffolds/simple/tsconfig.json
关联 PR：https://github.com/alibaba/ice/pull/4809
> feat: update ice map path in tsconfig

- .gitignore
- deprecated-components/layout/CHANGELOG.md
- deprecated-components/layout/package.json
这种情况要么加上 es 要么在 package.json 里补充 stylePath 字段
> fix: add es & stylepath to layout

- scaffolds/ice3-antd-pro/README.md
- scaffolds/ice3-antd-pro/ice.config.mts
- scaffolds/ice3-antd-pro/package.json
- scaffolds/ice3-lite/README.md
- scaffolds/ice3-lite/package.json
- scaffolds/ice3-miniapp/README.md
- scaffolds/ice3-miniapp/package.json
> chore: ice package version

- scaffolds/ice3-miniapp/package.json
- scaffolds/ice3-miniapp/src/document.tsx
- scaffolds/ice3-miniapp/src/pages/index.module.css
> feat(miniapp): restore document.tsx and update button style

- scaffolds/ice3-antd-pro/ice.config.mts
- scaffolds/ice3-antd-pro/package.json
- scaffolds/ice3-fusion-pro/ice.config.mts
- scaffolds/ice3-fusion-pro/package.json
- scaffolds/ice3-lite/ice.config.mts
- scaffolds/ice3-lite/package.json
> feat: support minify of swc

- scaffolds/ice3-miniapp/package.json
--platform CLI 参数不可用，使用 --target 代替
> fix: cli option platform is invalid

- scaffolds/ice3-antd-pro/package.json
- scaffolds/ice3-antd-pro/src/app.ts
- scaffolds/ice3-fusion-pro/package.json
- scaffolds/ice3-fusion-pro/src/app.ts
- scaffolds/ice3-icestark-child/package.json
- scaffolds/ice3-icestark-child/src/app.tsx
- scaffolds/ice3-icestark-layout/package.json
- scaffolds/ice3-icestark-layout/src/app.ts
Ref: https://github.com/alibaba/ice/pull/5981
> feat: update plugin module id import

- scaffolds/ice3-antd-pro/ice.config.mts
- scaffolds/ice3-antd-pro/package.json
- scaffolds/ice3-fusion-pro/ice.config.mts
- scaffolds/ice3-fusion-pro/package.json
- scaffolds/ice3-icestark-child/ice.config.mts
- scaffolds/ice3-icestark-child/package.json
- scaffolds/ice3-icestark-layout/ice.config.mts
- scaffolds/ice3-icestark-layout/package.json
- scaffolds/ice3-lite/ice.config.mts
- scaffolds/ice3-lite/package.json
> fix: update scaffolds

- scaffolds/ice3-lite/package.json
- scaffolds/ice3-lite/tsconfig.json
> chore: change tsconfig

- scaffolds/ice3-antd-pro/package.json
- scaffolds/ice3-fusion-pro/package.json
- scaffolds/ice3-lite/package.json
Update scaffold when @ice/app@3.3.0 is published.
> chore: update @ice/app

- scaffolds/ice3-antd-pro/package.json
- scaffolds/ice3-icestark-layout/package.json
- scaffolds/ice3-icestark-layout/src/app.ts
- scaffolds/ice3-lite/package.json
Tip: fusion pro scaffold have some build error when use `tnpm` as package management. It will be update later when the error is been resolved.
> feat: use the latest @ice/app and add tips for @ice/stark scaffold
